# Use the official Node.js image as the base image
FROM node:16.14 AS build

# Set the working directory in the container
WORKDIR /app

# Install Angular CLI globally
RUN npm install -g @angular/cli@16

# Copy package.json and package-lock.json to the container
#COPY package.json ./

# Install project dependencies
#RUN npm install

# Copy the entire project to the container
COPY . .

EXPOSE 4200
# Build the Angular application
#CMD ["ng", "build", "--watch", "--configuration=development"]
CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4200", "--watch"]